---

- name: Install Elastic apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic apt repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    state: present

- name: Install Filebeat
  apt:
    name: filebeat
    update_cache: yes
    state: present

- name: Start filebeat
  service:
    name: filebeat
    state: started
    enabled: yes
