---

- name: restart application
  supervisorctl: name={{ application_name }} state=restarted

- name: restart tessera
  supervisorctl: name={{ application_name }}-tessera state=restarted

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded