---

- name: Provision a {{ application_name }} tileserver
  hosts: tileservers
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml

  roles:
    - base
    - tileserver