---

- name: Provision a {{ application_name }} tileserver
  hosts: 127.0.0.1
  sudo: yes
  sudo_user: root
  remote_user: ubuntu
  vars:
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/production-tileserver.yml

  roles:
    - base
    - tileserver