---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
    - deployment_env: vagrant
    #- ipython_notebook: yes

  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"

  roles:
    - base
    - memcached
    - db
    - rabbitmq
    - web
    - celery
    - filebeat
    - metricbeat
    - prediction-models
