---

- name: restart application
  supervisorctl: name={{ application_name }} state=restarted

- name: restart nginx
  systemd:
    state: restarted
    name: nginx
    enabled: yes

- name: reload nginx
  systemd:
    state: reloaded
    daemon_reload: yes
    name: nginx
    enabled: yes

- name: update full text column
  command: sudo -u postgres psql -d {{ db_name }} -c "UPDATE firestation_firedepartment SET fts_document=department_fts_document(id);"
