---
- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - libcurl4-openssl-dev
    - libssh2-1-dev
    - libgit2-dev
    - libgit2-24
    - libxml2-dev
    - libcurl4-gnutls-dev
    - libssl-dev
    - libmagick++-dev
    - libpq-dev
    - libxslt-dev
    - zlib1g-dev
    - build-essential
    - ranger
    - caca-utils
    - highlight
    - atool
    - w3m
    - poppler-utils 
    - mediainfo
  tags: packages

- name: Add CRAN apt repo
  apt_repository:
    repo: deb https://cran.rstudio.com/bin/linux/ubuntu xenial-cran35/
    state: present

- name: Add CRAN key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com
    id: E084DAB9

- name: Install R-base
  apt: name="r-base" update_cache=yes

- name: Install R-base
  apt: name="r-base-dev" update_cache=yes

- name: Install RScript
  apt: name="r-base-core" update_cache=yes

- name: Install RScript
  apt: name="r-cran-littler" update_cache=yes

- name: Install fire-risk dependencies
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item.name }}' %in% installed.packages()[,'Package'])) { install.packages('{{ item.name }}', repos='https://cloud.r-project.org', dependencies=c('Depends','Imports'), verbose=TRUE); print('Added'); } else { print('Already installed'); }"
  with_items:
      - { name: 'tidyverse', version: '1.2.1' }
      - { name: 'glue', version: '1.3.1' }
      - { name: 'boot', version: '1.3-20' }
      - { name: 'git2r', version: '0.25.2' }
      - { name: 'glue', version: '1.3.1' }
      - { name: 'usethis', version: '1.5.0' }
      - { name: 'devtools', version: '2.0.1' }
      - { name: 'DBI', version: '1.0.0' }
      - { name: 'Matrix', version: '1.0.0' }
      - { name: 'glmnet', version: '2.0-16' }
      - { name: 'ranger', version: '0.11.2' }
      - { name: 'RPostgreSQL', version: '0.6-2' }
      - { name: 'lme4', version: '1.1-21' }
      - { name: 'magrittr', version: '1.5' }
      - { name: 'roxygen2', version: '6.1.1' }
      - { name: 'httr', version: '1.4.0' }
      - { name: 'acs', version: '1.4.0' }
      - { name: 'ranger', version: '1.4.0' }
  become: yes

- name: Install Census API key
  command: >
    Rscript --slave --no-save --no-restore-history -e "library.path <- .libPaths(); library(acs, lib.loc = library.path); api.key.install('{{ census_api_key }}')"
  when: census_api_key is defined

