---
- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - libssh2-1-dev
    - libgit2-dev
    - libgit2-0
    - libgit2-dbg
    - libcurl4-gnutls-dev
    - libxml2-dev
    - libssl-dev
    - libmagick++-dev
  tags: packages

- name: Add CRAN apt repo
  apt_repository:
    repo: deb https://cran.rstudio.com/bin/linux/ubuntu trusty/
    state: present

- name: Add CRAN key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com
    id: E084DAB9

- name: Install R-base
  apt: name="r-base" update_cache=yes


- name: Install glue specific version
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages('{{ item }}', dependencies=TRUE, repos='http://cran.us.r-project.org'); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
      - glue
      - usethis
      - devtools

- name: Install fire-risk dependencies
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('https://cloud.r-project.org/')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items:
      - acs
      - glmnet
      - git2r
      - ranger
      - RPostgreSQL
      - lme4
      - boot
      - magrittr
      - roxygen2

- name: Install Census API key
  command: >
    Rscript --slave --no-save --no-restore-history -e "library(acs); api.key.install('{{ census_api_key }}')"
  when: census_api_key is defined
