---
galaxy_info:
  author: Johan Meiring
  description: "Setup chrooted SFTP service on top of OpenSSH"
  license: MIT
  min_ansible_version: 1.5

  platforms:
  - name: Ubuntu
    versions:
    - all

  categories:
  - networking
  - system

dependencies: []
