---

- name: Create the application user
  user: name={{ gunicorn_user }} state=present

- name: Allow for sudo for {{ gunicorn_user }}
  user: name={{ gunicorn_user }} state=present groups="sudo" append=yes
  when: development_niceties is defined and development_niceties

- name: Allow 'sudo' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL:ALL) NOPASSWD:ALL'
  when: development_niceties is defined and development_niceties

- name: Create the application group
  group: name={{ gunicorn_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ gunicorn_user }} group={{ gunicorn_group }} state=present

- name: Allow SSH as {{ gunicorn_user }} user
  shell: echo '{{ gunicorn_user }}:{{ gunicorn_user }}' | chpasswd
  when: development_mode is defined and development_mode

- name: Do not Allow SSH as {{ gunicorn_user }} user
  shell: passwd -d {{ gunicorn_user }}
  when: development_mode is defined and not development_mode
