---

- include: install_additional_packages.yml
  tags: packages

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml
  tags: virtualenv

- include: setup_git_repo.yml
  tags: deploy

- include: setup_sym_linked_repo.yml
  tags: deploy

- include: setup_django_app.yml
  tags: deploy

- include: setup_supervisor.yml
  tags: supervisor

- include: set_file_permissions.yml
  tags: deploy

- include: setup_nginx.yml
  tags: nginx

- include: ipython_notebook.yml
  tags: ipython_notebook

- include: update_fixtures.yml
  tags: update_fixtures
  when: update_fixtures | bool

- include: maintenance.yml
  when: maintenance_mode | default('no') | bool

- include: sitemap.yml
  tags: sitemap
