---

# Application settings.
virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/requirements.txt"


# Gunicorn settings
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps


# Nginx settings
nginx_http_port: 80
nginx_https_port: 443
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "/var/www/firecares/static/"
nginx_media_dir: "/var/www/firecares/media/"


# Django Environment variables
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  EMAIL_HOST: "{{ email_host|default(omit) }}"
  EMAIL_HOST_USER: "{{ email_host_user|default(omit) }}"
  EMAIL_HOST_PASSWORD: "{{ email_host_password|default(omit) }}"
  BROKER_URL: "{{ broker_url|default(omit) }}"
  AWS_STORAGE_BUCKET_NAME: "{{ aws_storage_bucket_name|default(omit) }}"
  AWS_ACCESS_KEY_ID: "{{ aws_access_key_id|default(omit) }}"
  AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key|default(omit) }}"
  MAPBOX_ACCESS_TOKEN: "{{ mapbox_access_token|default(omit) }}"
  GOOGLE_ANALYTICS_TRACKING_ID: "{{ google_analytics_tracking_id|default(omit) }}"
  DATABASE_NAME: "{{ database_name }}"
  DATABASE_USER: "{{ database_user }}"
  DATABASE_PASSWORD: "{{ database_password }}"
  DATABASE_HOST: "{{ database_host }}"
  DATABASE_PORT: "{{ database_port }}"
  NFIRS_DATABASE_NAME: "{{ nfirs_database_name }}"
  NFIRS_DATABASE_USER: "{{ nfirs_database_user }}"
  NFIRS_DATABASE_PASSWORD: "{{ nfirs_database_password }}"
  NFIRS_DATABASE_HOST: "{{ nfirs_database_host }}"
  NFIRS_DATABASE_PORT: "{{ nfirs_database_port }}"
  MEMCACHE_LOCATION: "{{ memcache_location }}"
  EMAIL_HOST: "{{ email_host }}"
  EMAIL_HOST_PASSWORD: "{{ email_host_password }}"
  EMAIL_HOST_USER: "{{ email_host_user }}"
  EMAIL_PORT: "{{ email_port }}"
  SERVER_EMAIL: "{{ server_email }}"
  DEFAULT_FROM_EMAIL: "{{ default_from_email }}"
  SLACK_TOKEN: "{{ slack_token|default(omit) }}"
  SLACK_CHANNEL: "{{ slack_channel }}"
  SLACK_ICON_EMOJI: "{{ slack_icon_emoji }}"
  SLACK_USERNAME: "{{ slack_username }}"
  SLACK_FIRECARES_COMMAND_TOKEN: "{{slack_firecares_command_token}}"
  CELERY_RESULT_BACKEND: "cache+memcached://{{memcache_location}}"
  DOCUMENT_UPLOAD_BUCKET: "{{document_upload_bucket}}"
  HELIX_SECRET: "{{ helix_secret|default(omit) }}"
  COMPRESS_URL: "{{compress_url|default(omit)}}"
