---

- include: create_swap_file.yml
  when: create_swap_file
  tags: swap

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=latest
  with_items:
    - bash
    - openssl
    - libssl-dev
    - libssl-doc
  tags: packages

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - build-essential
    - ntp
    - htop
    - git
    - libpq-dev
    - python-dev
    - python-pip
    - python-pycurl
    - python-psycopg2
    - supervisor
    - binutils
    - libproj-dev
    - gdal-bin
    - python-gdal
    - libpng-dev
    - libfreetype6-dev
    - pkg-config
    - libjpeg-dev
    - libblas-dev
    - liblapack-dev
    - libatlas-base-dev
    - gfortran
    - unattended-upgrades
    - libxml2-dev
    - libxslt-dev
    - libffi-dev
    - postgis
  tags: packages

- name: activate unattended-upgrades
  lineinfile: dest=/etc/apt/apt.conf.d/10periodic line='APT::Periodic::Unattended-Upgrade "1";'
  tags: packages

- name: add auto upgrades
  lineinfile: dest=/etc/apt/apt.conf.d/20auto-upgrades create=yes line='{{item}}'
  tags: packages
  with_items:
    - 'APT::Periodic::Update-Package-Lists "1";'
    - 'APT::Periodic::Unattended-Upgrade "1";'

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

- name: Install virtualenv
  pip: name=virtualenvwrapper
  tags: packages

- name: Install python security packages
  pip: name={{item}}
  tags: packages
  with_items:
    - ndg-httpsclient
    - pyOpenSSL
    - pyasn1

- name: copy esri extras
  copy: src=files/esri_extra.wkt dest=/usr/share/gdal/1.10 mode=0644

- name: install python
  pip: name={{ item }}
  with_items:
    - boto
    - awscli

- name: update curl
  script: roles/base/files/update-curl.sh

- name: Set up authorized_keys
  authorized_key: user={{ansible_ssh_user}} key="{{ item }}"
  with_file:
    - public_keys/jenkins
