---


- name: test
  shell: sudo apt-get update

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - python-software-properties
    - postgresql-client
    - nodejs-legacy
    - npm
  tags: packages

- name: intall boto
  pip: name=boto
  tags: packages


- npm: name={{item.name}} global=yes state=present version={{item.version}}
  with_items:
    - {'name': 'git://github.com/garnertb/tessera#firecares', 'version':''}
    - {'name':'tilelive-mapnik', 'version': '0.6.17'}
    - {'name': 'tilelive-mapbox', 'version': '0.4.0'}
    - {'name': 'tilelive-tmstyle', 'version': '0.4.2'}
    - {'name': 'git://github.com/mojodna/tilelive-merge#v1.0.2', 'version': ''}
    - {'name': 'mbtiles', 'version': '0.8.0'}
  tags: npm

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

- name: update ntp
  lineinfile: dest=/etc/ntp.conf regexp='^server {{item}}.ubuntu.pool.ntp.org' line='server {{item}}.amazon.pool.ntp.org iburst'
  with_items:
    - 0
    - 1
    - 2
    - 3