- name: Ensure that the application file permissions are set properly
  file: path={{ server_root_dir }}
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        state=directory
  notify: restart application
