---

- name: Setup the Git repo
  git: repo={{ git_repo }}
       version="{{ git_branch }}"
       dest={{ project_path }}
       accept_hostkey=yes
  when: setup_git_repo is defined and setup_git_repo
  tags: git

- name: Remove potentially old git repo
  file: dest={{ project_path }} state=absent
  when: sym_link_repo is defined and sym_link_repo and not setup_git_repo

- name: Setup the symlinked repo
  file: src={{ project_source }} dest={{ project_path }} state=link
  when: sym_link_repo is defined and sym_link_repo and not setup_git_repo

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Create the Gunicorn script file
  template: src=start_tessera.j2
            dest={{ virtualenv_path }}/bin/start_tileserver
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0755
            backup=no
  tags: deploy

- name: Create the tilestache configuration
  template: src=tileserver.j2
            dest={{ project_path }}/tileserver.cfg
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0755
            backup=no
  tags: deploy

- name: Create the tilestache configuration
  template: src=tileserver.j2
            dest={{ project_path }}/tileserver.cfg
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0755
            backup=no
  tags: deploy

- name: Create the tessera configuration
  template: src=tessera.j2
            dest={{ project_path }}/tessera.json
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0755
            backup=no
  tags: deploy
  notify:
    - restart tessera

- name: Create the parcels mapnik configuration
  template: src=parcels.xml.j2
            dest={{ project_path }}/parcels.xml
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0755
            backup=no
  tags: deploy
  notify:
    - restart tessera

- name: Ensure that the application file permissions are set properly
  file: path={{ tiles_path }}
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        state=directory

- get_url: url="https://s3.amazonaws.com/firecares-tiles/{{item}}" dest={{tiles_path}}/{{item}} force=yes
  with_items: "{{tiles}}"
  tags: mbtiles.download

- name: Ensure that the tiles file permissions are set properly
  file: path={{ tiles_path }}
        recurse=yes
        owner={{ gunicorn_user }}
        group={{ gunicorn_group }}
        state=directory
  tags: mbtiles.perms

- name: Create the Gunicorn script file
  template: src=gunicorn_start_tileserver.j2
            dest={{ virtualenv_path }}/bin/gunicorn_start_tileserver
            owner={{ gunicorn_user }}
            group={{ gunicorn_group }}
            mode=0755
            backup=no
  tags: deploy